### PR TITLE
folding in nanz' feedback

### PR DESCRIPTION
**Pull request by mixmix**
selection_242

Had a great conversation with Nanz last night. Happy to speak on phone about what advice went into some of moving things around.
I'm really excited about how much more readible this take is looking already

### CODE REVIEW

**Comment by pietgeursen** [comment]
OOOOOHHHHH Yeah! Really like the direction this is going. 
Great job @mixmix. Yay for Nanz.

**Comment by pietgeursen** [comment]
It looks a bit different in Chrome btw.

**Comment by mixmix** [comment]
Annoying! Will look when i get home

**Comment by dominictarr** [comment]
that looks good.
what does it look like on a phone?

**Comment by mixmix** [comment]
good question. Tweaked a little, will push what I've done further now

**Comment by mixmix** [comment]
Yeah I think this is much better and we should merge it.

Things that might need work : 
- [ ] some different sizing of headers when mobile
- [ ] a protozoa image that is creative commons (check out the B+W one [here](https://hiveminer.com/Tags/protozoa/Timeline))

**Pull request merged**
