### PR TITLE
make 'who' section responsive.

### PR DESCRIPTION
**Pull request by dominictarr**
lol, don't use tables!

it would look better if it went from horizontal to vertical, but with bullet points beside the images, then to fully vertical, but this is good enough. at least no horizontal scrollbars!

### CODE REVIEW

**Comment by pietgeursen** [comment]
I got some sneaky pull requests merged ahead of you. This will require rebuilding after a rebase or merge.

**Comment by mixmix** [comment]
how does this look now @dominictarr

**Comment by mixmix** [comment]
Sorry, to clarify, I mean - I made changes to the site last night to address these things.

Can you have a look at what's live and see if it's sufficient

**Comment by dominictarr** [comment]
yup great, though one tiny thing: https://github.com/protozoa-nz/protozoa-nz.github.io/pull/22

**Pull request closed without merging**
